# Generated by Django 4.0.6 on 2022-10-02 12:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_pool', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=44, size=4)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
